---
- hosts: 192.168.197.87
  user: root
  become: yes
 # connection: ssh
  gather_facts: false
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/Mahesh/Test/Ajay
        state: directory
        mode: "0755"
