---
#- name: first file
 # hosts: Demo
 # becomes: Yes  
 # connection: ssh
 #gather_facts: flase
 
 - hosts: demo  

#  tasks:

#   - name: Ansible create directory and set permissions    
#
 #    file:
  #     path: /backups      

   #     state: directory      

    #    mode: "u=rw,g=wx,o=rwx"    

   #become: yes
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/some_directory
    state: directory
    mode: '0755'
